---
title: "Untitled"
author: "Arina"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(openxlsx)
```

```{r}
mh_med <- read.xlsx("./SDTM/MH_MEDICALHISTORY.xlsx")
adsl <-  read.xlsx("./SDTM/ADSL.xlsx")

```

```{r}
mh_med %>%
  glimpse()
```

```{r}
mh_med_1 <- 
  mh_med %>% 
  filter(MHCAT == "Medical History") %>%
  select(MHSEQ,MHCAT,MHTERM, MHDECOD, MHBODSYS, STUDYID, SUBJID) %>% 
  mutate(MHSEQ = as.integer(MHSEQ)) %>%
  mutate(MHTERM = ifelse(is.na(MHTERM), "Отсутствует", MHTERM))
  
```


```{r}
adsl %>%
  glimpse()
```

```{r}
adsl_1 <- adsl %>%
  select(STUDYID, USUBJID, TRTP, TRTPN, SUBJID) %>%
  mutate(TRTPN = as.integer(TRTPN))
```


#Работа с датами

```{r}
dates_mh_1 <- mh_med %>% 
  select(MHSEQ, MHSTDTC, MHENDTC, MHENRTPT, STUDYID, SUBJID) %>%
  mutate(MHSEQ = as.integer(MHSEQ),
         ASTDT = ifelse(nchar(MHSTDTC) == 4, format(as.Date(paste(MHSTDTC,"-01-01", sep=""), 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y"), ifelse(nchar(MHSTDTC) == 7, format(as.Date(paste(MHSTDTC,"-01", sep=""), 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y"),format(as.Date(MHSTDTC, format = "%Y-%m-%d"),"%d.%m.%Y"))),
         ASTDTF = ifelse(is.na(MHSTDTC),'Y',
                         ifelse(nchar(MHSTDTC) == 4, 'M', 
                        ifelse(nchar(MHSTDTC) == 7,'D',""))),
         MHENDTC = as.character(MHENDTC),
         AENDT = ifelse(MHENRTPT == 'ONGOING',"",  ifelse(nchar(MHENDTC) == 4, format(as.Date(paste(MHENDTC,"-01-01", sep=""), 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y"), ifelse(nchar(MHENDTC) == 7, format(as.Date(paste(MHENDTC,"-01", sep=""), 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y"),format(as.Date(MHENDTC, format = "%Y-%m-%d"),"%d.%m.%Y")))),
         AENDTF = ifelse(is.na(MHENDTC),'Y',
                         ifelse(nchar(MHSTDTC) == 4, 'M', 
                        ifelse(nchar(MHSTDTC) == 7,'D',""))),
         MHENRF = ifelse(MHENRTPT == 'ONGOING','ONGOING',"")
         ) 
  
```


```{r}
date <- left_join(adsl_1, mh_med_1) 
date_1 <- left_join(date, dates_mh_1)
date_1 <- filter(date_1, !is.na(MHTERM))
date_1 <- ADMH[,c("STUDYID","USUBJID","TRTP","TRTPN","MHSEQ", "MHCAT","MHTERM",
                "MHDECOD", "MHBODSYS", "MHSTDTC", "ASTDT", "ASTDTF", "MHENDTC",
                "AENDT", "AENDTF", "MHENRTPT", "MHENRF")]
ADMH_1 <- date_1 %>%
  relocate(ASTDT, .after = MHSTDTC) %>%
  relocate(ASTDTF, .after = ASTDT) %>%
  relocate(MHENRTPT, .after = AENDTF) 

```

```{r}
write.xlsx(ADMH, "./ADaM-like/ADMH.xlsx")
```

```{r}
ADMH %>%
  glimpse()
```

